version: '2'
services:

    #
    # minio
    #
    minio:
        image: mendersoftware/minio:RELEASE.2016-12-13T17-19-42Z
        networks:
            mender:
                aliases:
                    - minio.s3.docker.mender.io
        command: server /export

    #
    # storage backend proxy used in conjunction with minio, applies
    # rate & connection limiting
    #
    storage-proxy:
        image: mendersoftware/openresty:1.11.2.2-alpine
        networks:
            mender:
                aliases:
                    - s3.docker.mender.io
        depends_on:
            - minio
        volumes:
            - ./storage-proxy/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
