version: '2'
services:


    #
    # minio
    #
    minio:
        image: minio/minio:RELEASE.2016-12-13T17-19-42Z
        networks:
            mender:
                aliases:
                    # mender-artifact-storage.localhost must be mapped to 127.0.0.1
                    # running the 'up' script (found in this dir.) will add the required entry to /etc/hosts
                    - mender-artifact-storage.localhost
                    - mender-artifact-storage.s3.docker.mender.io
                    - minio.s3.docker.mender.io
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server /export

    #
    # storage backend proxy used in conjunction with minio, applies
    # rate & connection limiting
    #
    storage-proxy:
        image: openresty/openresty:alpine
        ports:
            - "9000:9000"
        networks:
            mender:
                aliases:
                    - s3.docker.mender.io
        environment:

            # use nginx syntax for rate limiting, see
            # https://nginx.org/en/docs/http/ngx_http_core_module.html#limit_rate
            # Examples:
            #   1m - 1MB/s
            #   512k - 512kB/s
            DOWNLOAD_SPEED: 1m
            MAX_CONNECTIONS: 100
        volumes:
            - ./storage-proxy/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
        depends_on:
            - minio

    #
    # mender-deployments
    #
    mender-deployments:
        image: mendersoftware/deployments:latest
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        # Application requires S3 access.
        # For convinience access can be configured here to overide config file.
        # Keys have to grant access to default bucket: mender-artifact-storage
        # Otherwhise provide config file though volume.
        #
        # The default docker-compose setup uses a fakes3 server, specified by the AWS_URI env. variable.
        environment:
             AWS_ACCESS_KEY_ID: minio
             AWS_SECRET_ACCESS_KEY: minio123
             AWS_URI: http://s3.docker.mender.io:9000
        depends_on:
            - mender-mongo-deployments

    mender-mongo-deployments:
        image: mongo:latest
        networks:
            mender:
                aliases:
                    - mongo-deployments

    #
    # mender-gui
    #
    mender-gui:
        image: mendersoftware/gui:latest
        networks:
            - mender

    #
    # mender-api-gateway
    #
    mender-api-gateway:
        image: mendersoftware/api-gateway:latest
        ports:
            - "8080:443"
        networks:
            mender:
                aliases:
                    - gateway
                    - docker.mender.io

        # nginx doesn't know the actual outside port
        # could be solved with introspection (mapping daemon socket + 'docker ps')
        # the easier way is an env var
        environment:
            MAPPED_PORT: 8080
        # critical - otherwise nginx may not detect
        # these servers and exits with 'upstream server not found'
        depends_on:
            - mender-device-auth
            - mender-device-adm
            - mender-deployments
            - mender-gui
            - mender-useradm
            - mender-inventory
        #mount production SSL cert/key from selected location
        #volumes:
        #    - /path/to/ssl/cert:/var/www/mendersoftware/cert/cert.pem
        #    - /path/to/ssl/key:/var/www/mendersoftware/cert/key.pem

    #
    # mender-device-auth
    #
    mender-device-auth:
        image: mendersoftware/deviceauth:latest
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo-device-auth

    mender-mongo-device-auth:
        image: mongo:latest
        networks:
            mender:
                aliases:
                    - mongo-device-auth

    #
    # mender-device-adm
    #
    mender-device-adm:
        image: mendersoftware/deviceadm:latest
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo-device-adm

    mender-mongo-device-adm:
        image: mongo:latest
        networks:
            mender:
                aliases:
                    - mongo-device-adm

    #
    # mender-inventory
    #
    mender-inventory:
        image: mendersoftware/inventory:latest
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo-inventory

    mender-mongo-inventory:
        image: mongo:latest
        networks:
            mender:
                aliases:
                    - mongo-inventory

    #
    # mender-useradm
    #
    mender-useradm:
        image: mendersoftware/useradm:latest
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo-useradm

    mender-mongo-useradm:
        image: mongo:latest
        networks:
            mender:
                aliases:
                    - mongo-useradm

networks:
    mender:
