version: '2.1'
services:

    #
    # mender-deployments
    #
    mender-deployments:
        image: mendersoftware/deployments:mender-master
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-gui
    #
    mender-gui:
        image: mendersoftware/gui:mender-master
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        environment:
            - GATEWAY_IP
            - INTEGRATION_VERSION
            - MENDER_ARTIFACT_VERSION
            - MENDER_VERSION
            - MENDER_DEB_PACKAGE_VERSION

    #
    # mender-api-gateway
    #
    mender-api-gateway:
        image: gateway-temp
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        # critical - otherwise nginx may not detect
        # these servers and exits with 'upstream server not found'
        depends_on:
            - mender-device-auth
            - mender-deployments
            - mender-gui
            - mender-useradm
            - mender-inventory
        labels:
            - traefik.enable=true
            - traefik.docker.network=mender
            - traefik.http.routers.gateway.tls=true
            - traefik.http.routers.gateway.entrypoints=https
            - traefik.http.routers.gateway.rule=PathPrefix(`/api/devices/v1/authentication`)
            - traefik.http.services.gateway.loadbalancer.server.port=443
            - traefik.http.services.gateway.loadbalancer.server.scheme=https

    traefik-ambassador:
        image: traefik:v2.1
        command: 
            - --api.insecure=true 
            - --providers.docker=true
            - --accesslog=true
            - --log.level=DEBUG
            - --entrypoints.http.address=:80
            - --entryPoints.https.address=:443
            - --providers.docker.network=mender
            - --providers.file.filename=/config/tls.toml

            - --serverstransport.insecureskipverify=true #allows self signed cert on gateway
        ports:
            - "9080:80"
            - "9081:8080"
            # avoid contention with mender-gateway - both want to expose the TLS port on localhost
            - "1443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            # for hot file reaload - mount the whole dir to avoid a changing inode on file edit
            - ./traefik-config:/config
        depends_on:
            - mender-api-gateway
        networks:
            - mender

    #
    # mender-device-auth
    #
    mender-device-auth:
        image: deviceauth-temp
        environment:
            DEVICEAUTH_ORCHESTRATOR_ADDR: http://mender-workflows-server:8080/
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo
            - mender-workflows-server

    #
    # mender-inventory
    #
    mender-inventory:
        image: mendersoftware/inventory:mender-master
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-useradm
    #
    mender-useradm:
        image: mendersoftware/useradm:mender-master
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo
        labels:
            - traefik.http.routers.useradm.tls=true
            - traefik.http.routers.useradm.entrypoints=https
            - traefik.http.routers.useradm.rule=PathPrefix(`/api/management/v1/useradm`)
            - traefik.http.services.useradm.loadbalancer.server.port=8080

    #
    # mender-workflows-server
    #
    mender-workflows-server:
        image: mendersoftware/workflows:mender-master
        environment:
            WORKFLOWS_MONGO_URL: mongodb://mender-mongo:27017
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-workflows-worker
    #
    mender-workflows-worker:
        image: mendersoftware/workflows-worker:mender-master
        command: worker --excluded-workflows generate_artifact
        environment:
            WORKFLOWS_MONGO_URL: mongodb://mender-mongo:27017
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-create-artifact-worker
    #
    mender-create-artifact-worker:
        image: mendersoftware/create-artifact-worker:mender-master
        environment:
            WORKFLOWS_MONGO_URL: mongodb://mender-mongo:27017
        extends:
            file: common.yml
            service: mender-base
        environment:
            - WORKFLOWS_MONGO_URL=mongodb://mongo-workflows:27017
            - CREATE_ARTIFACT_GATEWAY_URL=https://mender-api-gateway
            - CREATE_ARTIFACT_DEPLOYMENTS_URL=http://mender-deployments:8080
        networks:
            - mender
        depends_on:
            - mender-mongo

    mender-mongo:
        image: mongo:3.6
        extends:
            file: common.yml
            service: mender-base
        networks:
            mender:
                aliases:
                    - mongo-tenantadm
                    - mongo-deployments
                    - mongo-device-auth
                    - mongo-inventory
                    - mongo-useradm
                    - mongo-workflows

networks:
    mender:
