version: '2'
services:

    #
    # minio
    #
    minio:
        image: mendersoftware/minio:RELEASE.2016-12-13T17-19-42Z
        networks:
            mender:
                aliases:
                    # mender-artifact-storage.localhost must be mapped to 127.0.0.1
                    # running the 'up' script (found in this dir.) will add the required entry to /etc/hosts
                    - mender-artifact-storage.localhost
                    - mender-artifact-storage.s3.docker.mender.io
                    - minio.s3.docker.mender.io
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server /export

    #
    # storage backend proxy used in conjunction with minio, applies
    # rate & connection limiting
    #
    storage-proxy:
        image: mendersoftware/openresty:1.11.2.2-alpine
        ports:
            - "9000:9000"
        networks:
            mender:
                aliases:
                    - s3.docker.mender.io
        environment:

            # use nginx syntax for rate limiting, see
            # https://nginx.org/en/docs/http/ngx_http_core_module.html#limit_rate
            # Examples:
            #   1m - 1MB/s
            #   512k - 512kB/s
            DOWNLOAD_SPEED: 1m
            MAX_CONNECTIONS: 100
        depends_on:
            - minio

    #
    # mender-deployments
    #
    mender-deployments:
        # Minio access configuration
        # Keys have to grant access to default bucket: mender-artifact-storage
        environment:
             AWS_ACCESS_KEY_ID: minio
             AWS_SECRET_ACCESS_KEY: minio123
             AWS_URI: https://s3.docker.mender.io:9000
